I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 34, in script call
    pause
  File "game/script.rpy", line 20, in script
    $ inventory_items.append("bone", item)
  File "game/script.rpy", line 20, in <module>
    $ inventory_items.append("bone", item)
TypeError: list.append() takes exactly one argument (2 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script call
    pause
  File "game/script.rpy", line 20, in script
    $ inventory_items.append("bone", item)
  File "/Users/emilyamspoker/renpy-8.2.1-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/emilyamspoker/renpy-8.2.1-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 20, in <module>
    $ inventory_items.append("bone", item)
  File "/Users/emilyamspoker/renpy-8.2.1-sdk/renpy/revertable.py", line 97, in do_mutation
    return method(self, *args, **kwargs)
TypeError: list.append() takes exactly one argument (2 given)

macOS-12.3-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
Paws and Play 1.0
Thu Apr  4 14:31:16 2024
